declare  
  v_tbl_name varchar2(100) := 'R_BOE_SALES_ORD';   
  v_fld_vals varchar2(4000); 
   
  v_num_types arrayofstrings := arrayofstrings('NUMBER'); 
 
  v_min_val number; 
  v_avg_val number; 
  v_max_val number; 
   
  v_num_vals_str varchar2(2000); 
   
begin 
       
      for rw in ( select column_name 
                           , data_type 
                                           , length(column_name) as col_len 
                                                           , max(length(column_name)) over () as max_col_len 
                                                                        from user_tab_cols 
                                                                                       where table_name = upper(v_tbl_name)  
                                                                                                     and column_name not like 'SYS_%'  
                                                                                                                   order by column_name) 
                                                                                                              loop 
                                                                                                                     
                                                                                                                    execute immediate 'select listagg(sq.field_value, '','')  
                                                                                                                                                      within group(order by 1) as field_values 
                                                                                                                                                                             from ( select distinct ' || rw.column_name || ' as field_value 
                                                                                                                                                                                                                  from ' || v_tbl_name || ' t 
                                                                                                                                                                                                                                                 where rownum < 6  
                                                                                                                                                                                                                                                                                   and ' || rw.column_name || ' is not null 
                                                                                                                                                                                                                                                                                                                ) sq' 
                                                                                                                                                                                                                                                                                                                    into v_fld_vals; 
                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                        for x in ( select 1 from table(v_num_types) where column_value = rw.data_type ) 
                                                                                                                                                                                                                                                                                                                                loop 
                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                          execute immediate 'select cast(min(rw.column_name) as number(25,2)) as min_val 
                                                                                                                                                                                                                                                                                                                                                                      , cast(avg(rw.column_name) as number(25,2)) as avg_val 
                                                                                                                                                                                                                                                                                                                                                                                                  , cast(max(rw.column_name) as number(25,2)) as max_val  
                                                                                                                                                                                                                                                                                                                                                                                                                         from   ' || v_tbl_name || ' t' 
                                                                                                                                                                                                                                                                                                                                                                                                                              into v_min_val, v_avg_val, v_max_val; 
                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                  v_num_vals_str := 'Min: ' || v_min_val || ' Avg: ' || v_avg_val || ' Max: ' || v_max_val; 
                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                    end loop; 
                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                        dbms_output.put_line('*** '|| rw.column_name || ' ***: ' || rpad(' ', rw.max_col_len-rw.col_len, ' ') || (case when v_fld_vals is null then 'NULL' else v_fld_vals|| ',...' end)); 
                                                                                                                                                                                                                                                                                                                                                                                                                                            dbms_output.put_line(v_num_vals_str); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                dbms_output.put_line('-------------------------------------------------------------------------------------'); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                  end loop; 
                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    end; 
